CREATE TABLE stocks (
    stock_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(255) NOT NULL,
    sector_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE validation_outbox (
    validation_outbox_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trade_id UUID NOT NULL,
    portfolio_id UUID NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(50) NOT NULL,
    price_per_stock NUMERIC(19,4) NOT NULL,
    quantity BIGINT NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE processed_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id UUID NOT NULL,
    consumer_group VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL DEFAULT now(),
    version BIGINT DEFAULT 0,
    UNIQUE (event_id, consumer_group)
);
